<a href="https://colab.research.google.com/github/RabinPhuyal/Deep-Learning-with-Pytorch/blob/main/Tensors%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Importing PyTorch

In [ ]:
import torch

In [ ]:
### Listing Installed Packages

In [ ]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.5
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                         

In [ ]:
### Checking Torch Version

In [ ]:
torch.__version__

'2.10.0+cu128'

In [ ]:
### Python List Overview

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
my_list_2d = [[1,2,3],[4,5,6],[7,8,9]]
my_list_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
### Numpy Array Overview

In [ ]:
import numpy as np

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.91303118, 0.46523718, 0.57410768, 0.18962139],
       [0.89735594, 0.80067322, 0.3009941 , 0.71752122],
       [0.17731693, 0.6094336 , 0.50755728, 0.24373093]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
### Introdution to Tensors

In [ ]:
tensor_2d =  torch.randn(3,4)
tensor_2d

tensor([[ 0.0306, -0.4756, -0.7215,  0.0391],
        [ 0.2869, -0.4804, -0.6775,  1.9129],
        [ 0.0496, -0.8849,  0.3836, -1.5012]])

In [ ]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.1932,  0.3604,  0.9609, -1.9889],
         [-1.4339, -1.1732,  0.5624,  0.4134],
         [-0.7208,  0.9918,  0.8245, -2.0875]],

        [[ 0.3152, -1.5223, -1.1435,  0.4872],
         [-0.2407,  0.2434, -1.5703, -1.1347],
         [ 1.0899, -0.5399,  0.9298,  0.2097]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9130, 0.4652, 0.5741, 0.1896],
        [0.8974, 0.8007, 0.3010, 0.7175],
        [0.1773, 0.6094, 0.5076, 0.2437]], dtype=torch.float64)

In [ ]:
# Zero Dimension Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# One Dimension Tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Two Dimension Tensor
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Multidimensional Tensor
tensor_random = torch.rand(2,3,4)
tensor_random.shape,tensor_random.dtype

(torch.Size([2, 3, 4]), torch.float32)

In [ ]:
tensor_random_image_size = torch.randn(224,224,3)
tensor_random_image_size.shape, tensor_random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Creating a tensor with all zeros
zeros = torch.zeros(size=(1,2,3))
zeros,zeros.dtype

(tensor([[[0., 0., 0.],
          [0., 0., 0.]]]),
 torch.float32)

In [ ]:
# Creating a tensor with all ones
ones = torch.ones(size=(2,3,4))
ones,ones.dtype

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.float32)

In [ ]:
#Creating a tesnor with arange
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten,zero_to_ten.shape,zero_to_ten.ndim

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]), 1)

In [ ]:
#Creating another tensor similar to previous one with all zeros
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Getting information from tensors
tensors = torch.rand(3,4)

print(tensors)
print(f"Shape of tensor is: {tensors.shape}")
print(f"Data type of tensor is: {tensors.dtype}")
print(f"Device stored tensor is: {tensors.device}")

tensor([[0.7769, 0.5471, 0.3744, 0.4475],
        [0.7842, 0.3014, 0.0787, 0.5268],
        [0.0121, 0.8090, 0.4587, 0.2295]])
Shape of tensor is: torch.Size([3, 4])
Data type of tensor is: torch.float32
Device stored tensor is: cpu


In [ ]:
###Manipulating Tensors

#Additions
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiplications
tensor*10

tensor([10, 20, 30])

In [ ]:
#Substitution
tensor = tensor-10
tensor

tensor([-29, -28, -27])

In [ ]:
#Element wise multiplication
print(f"{tensor} * {tensor} Equals {tensor*tensor}")

tensor([-29, -28, -27]) * tensor([-29, -28, -27]) Equals tensor([841, 784, 729])


In [ ]:
### Matrix Multiplications
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[4,5],[1,2],[1,1]])

result = torch.matmul(tensor1,tensor2)
print(result)

tensor([[ 9, 12],
        [27, 36]])


In [ ]:
result = tensor1 @ tensor2
result

tensor([[ 9, 12],
        [27, 36]])

In [ ]:
result.T

tensor([[ 9, 27],
        [12, 36]])

In [ ]:
#Aggregation in Tensors

x= torch.arange(0,100,10)

#Finding the maximum
print(f"Maximum: {x.max()}")

#Finding the minimum
print(f"Minimum: {x.min()}")

#Finding the mean
print(f"Mean: {x.type(torch.float32).mean()}")

#Finding the sum
print(f"Sum: {x.sum()}")

Maximum: 90
Minimum: 0
Mean: 45.0
Sum: 450


In [ ]:
x = torch.arange(0,100,10)

torch.min(x),torch.max(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [ ]:
x = torch.arange(10,100,10)

print(f"Tensors: {x}")
print(f"Max element at index: {x.argmax()}")
print(f"Min element at index: {x.argmin()}")

torch.argmax(x),torch.argmin(x)

Tensors: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Max element at index: 8
Min element at index: 0


(tensor(8), tensor(0))

In [ ]:
tensor = torch.arange(10.,100.,10.)

tensor.dtype


torch.float32

In [ ]:
tensor_float64 = tensor.type(torch.float64)
tensor_float64

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
#Reshaping, Stacking, Squeezing and Unsequezing

import torch

x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
#View example
z =x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:,5] = 0
z,x

(tensor([[1., 2., 3., 4., 5., 0., 7.]]), tensor([1., 2., 3., 4., 5., 0., 7.]))

In [ ]:
#Stacke tensor on top of each other

x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 0., 7.],
        [1., 2., 3., 4., 5., 0., 7.],
        [1., 2., 3., 4., 5., 0., 7.],
        [1., 2., 3., 4., 5., 0., 7.]])

In [ ]:
#Stacke tensor on top of each other

x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [0., 0., 0., 0.],
        [7., 7., 7., 7.]])

In [ ]:
#Squeezing

print(f"Previous tensor: {x_reshaped}")
print(f"Previour shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"Squeezed tensor: {x_squeezed}")
print(f"Squeezed shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 0., 7.]])
Previour shape: torch.Size([1, 7])
Squeezed tensor: tensor([1., 2., 3., 4., 5., 0., 7.])
Squeezed shape: torch.Size([7])


In [ ]:
#UnSqueezing

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"Unsqueezed Tensor: {x_unsqueezed}")
print(f"Unsqueezed Shape: {x_unsqueezed.shape}")

Unsqueezed Tensor: tensor([[1., 2., 3., 4., 5., 0., 7.]])
Unsqueezed Shape: torch.Size([1, 7])


In [ ]:
#Permuted

x_original = torch.rand(size=(6,7,8,9))

x_premuted = x_original.permute(3,2,0,1)

print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_premuted.shape}")

Original shape: torch.Size([6, 7, 8, 9])
Permuted shape: torch.Size([9, 8, 6, 7])


In [ ]:
#Indexing
x = torch.arange(1,19).reshape(2,3,3)

print(x)
print(f"First Bracket: \n{x[0]}")
print(f"Second Bracket: {x[0][0]}")
print(f"Third Bracket: {x[0][0][0]}")

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
First Bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second Bracket: tensor([1, 2, 3])
Third Bracket: 1


In [ ]:
x[:,0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [ ]:
x[:,:,1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [ ]:
x[1,:,:]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [ ]:
x[:,1,1]

tensor([ 5, 14])

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch1 = my_torch.reshape(-1,2)
my_torch1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [1]:
#Pytorch Tensors and Numpy

#From Numpy array to tensors

import torch
import numpy as np

ndarray = np.arange(1.0,8.0)
tensor = torch.from_numpy(ndarray)
ndarray,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
#Changing array, keeping the tensor same
ndarray = ndarray+1
ndarray,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
#From tensor to numpy array

tensor = torch.arange(1.0,8.0)
ndarray = tensor.numpy()
tensor,ndarray

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [4]:
#Changing Tensor, keeping array same

tensor=tensor+1
tensor,ndarray

(tensor([2., 3., 4., 5., 6., 7., 8.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))